### ISSUE TITLE
[Watermark plugin] DOMException: Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by cedricdelpoux** [microsoft/roosterjs#1387]
**Describe the bug**
When using [Watermark plugin](https://microsoft.github.io/roosterjs/docs/classes/roosterjs_editor_plugins.watermark.html), I get a `DOMException` error.

**To Reproduce**
2. Create new RoosterJs instance with Watermark plugin

```
import { Editor } from 'roosterjs-editor-core'

new Editor(element, {
  plugins: [
    new Watermark(),
  ]
})
```

2. See error in the console

```
DOMException: Failed to execute 'insertBefore' on 'Node': This node type does not support this method.
    at eval (webpack-internal:///./node_modules/roosterjs-editor-core/lib/coreApi/insertNode.js:70:50)
    at Object.transformColor (webpack-internal:///./node_modules/roosterjs-editor-core/lib/coreApi/transformColor.js:40:57)
    at Object.insertNode (webpack-internal:///./node_modules/roosterjs-editor-core/lib/coreApi/insertNode.js:42:14)
    at Editor.insertNode (webpack-internal:///./node_modules/roosterjs-editor-core/lib/editor/Editor.js:81:37)
    at insertEntity (webpack-internal:///./node_modules/roosterjs-editor-api/lib/format/insertEntity.js:47:16)
    at Watermark.showHideWatermark (webpack-internal:///./node_modules/roosterjs-editor-plugins/lib/plugins/Watermark/Watermark.js:27:57)
    at Watermark.onPluginEvent (webpack-internal:///./node_modules/roosterjs-editor-plugins/lib/plugins/Watermark/Watermark.js:82:18)
    at eval (webpack-internal:///./node_modules/roosterjs-editor-core/lib/coreApi/triggerEvent.js:23:24)
    at Array.forEach (<anonymous>)
    at Object.triggerEvent (webpack-internal:///./node_modules/roosterjs-editor-core/lib/coreApi/triggerEvent.js:21:22)
```

**Expected behavior**
No error

**Screenshots**

<img width="1017" alt="Screenshot 2022-11-07 at 14 04 10" src="https://user-images.githubusercontent.com/2683300/200317382-448ea5bd-7c98-43e8-bfcc-2f6408e0a3ec.png">

**Device Information**
 - OS: MacOS Ventura 13
 - Browser Brave
 - Version  1.45.18

**Comment by cedricdelpoux** [comment]
Closing because I can't reproduce anymore. I will re open later the bug reappears
