### ISSUE TITLE
Test suite tableResizerTest is unstable

### ISSUE THREAD

**Issue by JiuqingSong** [microsoft/roosterjs#2474]
Got different kinds of failure randomly:

![image](https://github.com/microsoft/roosterjs/assets/23065085/0ebd54eb-0121-474b-961d-3053e14d5817)

```
Chrome 122.0.0.0 (Windows 10) Table Resizer tests increases the width of the table FAILED
        Uncaught Error: Editor is already disposed thrown
        Error: Editor is already disposed
            at Editor.getCore (webpack://roosterjs/packages/roosterjs-content-model-core/lib/editor/Editor.ts:381:19 <- karma.test.all.1493455491.js:37466:19)
            at Editor.getVisibleViewport (webpack://roosterjs/packages/roosterjs-content-model-core/lib/editor/Editor.ts:372:21 <- karma.test.all.1493455491.js:37458:21)
            at isTableBottomVisible (webpack://roosterjs/packages/roosterjs-content-model-plugins/lib/tableEdit/editors/features/TableResizer.ts:237:36 <- karma.test.all.1493455491.js:107224:34)
            at Object.onDragEnd (webpack://roosterjs/packages/roosterjs-content-model-plugins/lib/tableEdit/editors/features/TableResizer.ts:203:9 <- karma.test.all.1493455491.js:107203:9)
            at DragAndDropHelper.onMouseUp (webpack://roosterjs/packages/roosterjs-content-model-plugins/lib/pluginUtils/DragAndDrop/DragAndDropHelper.ts:145:35 <- karma.test.all.1493455491.js:105733:95)
            at moveAndResize (webpack://roosterjs/packages/roosterjs-content-model-plugins/test/tableEdit/TableEditTestHelper.ts:213:19 <- karma.test.all.1493455491.js:135002:19)
            at resizeWholeTableTest (webpack://roosterjs/packages/roosterjs-content-model-plugins/test/tableEdit/tableResizerTest.ts:105:22 <- karma.test.all.1493455491.js:136594:49)
            at UserContext.<anonymous> (webpack://roosterjs/packages/roosterjs-content-model-plugins/test/tableEdit/tableResizerTest.ts:175:9 <- karma.test.all.1493455491.js:136642:9)
            at <Jasmine>
        Error: Expected false to be true.
            at <Jasmine>
            at webpack://roosterjs/packages/roosterjs-content-model-plugins/test/tableEdit/tableResizerTest.ts:167:21 <- karma.test.all.1493455491.js:136636:97
            at <Jasmine>
            at compareTableRects (webpack://roosterjs/packages/roosterjs-content-model-plugins/test/tableEdit/tableResizerTest.ts:163:29 <- karma.test.all.1493455491.js:136634:29)
Chrome 122.0.0.0 (Windows 10) Table Resizer tests increases the width of the table FAILED                                                                                                                                                                                          
        Uncaught Error: Editor is already disposed thrown
        Error: Editor is already disposed
            at Editor.getCore (webpack://roosterjs/packages/roosterjs-content-model-core/lib/editor/Editor.ts:381:19 <- karma.test.all.1493455491.js:37466:19)
            at Editor.getVisibleViewport (webpack://roosterjs/packages/roosterjs-content-model-core/lib/editor/Editor.ts:372:21 <- karma.test.all.1493455491.js:37458:21)
            at isTableBottomVisible (webpack://roosterjs/packages/roosterjs-content-model-plugins/lib/tableEdit/editors/features/TableResizer.ts:237:36 <- karma.test.all.1493455491.js:107224:34)
            at Object.onDragEnd (webpack://roosterjs/packages/roosterjs-content-model-plugins/lib/tableEdit/editors/features/TableResizer.ts:203:9 <- karma.test.all.1493455491.js:107203:9)
            at DragAndDropHelper.onMouseUp (webpack://roosterjs/packages/roosterjs-content-model-plugins/lib/pluginUtils/DragAndDrop/DragAndDropHelper.ts:145:35 <- karma.test.all.1493455491.js:105733:95)
            at moveAndResize (webpack://roosterjs/packages/roosterjs-content-model-plugins/test/tableEdit/TableEditTestHelper.ts:213:19 <- karma.test.all.1493455491.js:135002:19)
            at resizeWholeTableTest (webpack://roosterjs/packages/roosterjs-content-model-plugins/test/tableEdit/tableResizerTest.ts:105:22 <- karma.test.all.1493455491.js:136594:49)
            at UserContext.<anonymous> (webpack://roosterjs/packages/roosterjs-content-model-plugins/test/tableEdit/tableResizerTest.ts:175:9 <- karma.test.all.1493455491.js:136642:9)
            at <Jasmine>
        Error: Expected false to be true.
            at <Jasmine>
            at webpack://roosterjs/packages/roosterjs-content-model-plugins/test/tableEdit/tableResizerTest.ts:167:21 <- karma.test.all.1493455491.js:136636:97
            at <Jasmine>
            at compareTableRects (webpack://roosterjs/packages/roosterjs-content-model-plugins/test/tableEdit/tableResizerTest.ts:163:29 <- karma.test.all.1493455491.js:136634:29)
        Error: Editor is already disposed
            at Editor.getCore (webpack://roosterjs/packages/roosterjs-content-model-core/lib/editor/Editor.ts:381:19 <- karma.test.all.1493455491.js:37466:19)
            at Editor.dispose (webpack://roosterjs/packages/roosterjs-content-model-core/lib/editor/Editor.ts:57:27 <- karma.test.all.1493455491.js:37205:25)
            at afterTableTest (webpack://roosterjs/packages/roosterjs-content-model-plugins/test/tableEdit/TableEditTestHelper.ts:55:12 <- karma.test.all.1493455491.js:134871:12)
            at UserContext.<anonymous> (webpack://roosterjs/packages/roosterjs-content-model-plugins/test/tableEdit/tableResizerTest.ts:37:23 <- karma.test.all.1493455491.js:136539:50)
            at <Jasmine>
        Error: Editor is already disposed
            at EditorBase.getCore (webpack://roosterjs/packages/roosterjs-editor-core/lib/editor/EditorBase.ts:1035:19 <- karma.test.all.1493455491.js:150898:19)
            at EditorBase.dispose (webpack://roosterjs/packages/roosterjs-editor-core/lib/editor/EditorBase.ts:113:27 <- karma.test.all.1493455491.js:150152:25)
            at UserContext.<anonymous> (webpack://roosterjs/packages/roosterjs-editor-plugins/test/ContentEdit/features/shortcutFeatureTest.ts:15:12 <- karma.test.all.1493455491.js:196636:12)
            at <Jasmine>
```

**Comment by Andres-CT98** [comment]
Fixed in #2487
